# Generated by Django 5.1.5 on 2025-01-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key_skills', models.TextField()),
                ('salary_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_currency', models.CharField(max_length=10)),
                ('area_name', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
