# Generated by Django 5.1.5 on 2025-01-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URFU_PROJECT_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
