# Generated by Django 5.1.5 on 2025-01-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URFU_PROJECT_APP', '0002_alter_profession_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('eur', models.DecimalField(decimal_places=4, max_digits=10)),
                ('kzt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('uah', models.DecimalField(decimal_places=4, max_digits=10)),
                ('byr', models.DecimalField(decimal_places=4, max_digits=10)),
                ('azn', models.DecimalField(decimal_places=4, max_digits=10)),
                ('uzs', models.DecimalField(decimal_places=4, max_digits=10)),
                ('kgs', models.DecimalField(decimal_places=4, max_digits=10)),
                ('gel', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='profession',
            name='published_at',
            field=models.DateTimeField(),
        ),
    ]
